package main

var FirstName = []string{
	"John",
	"Alex",
	"Tony",
	"Chris",
	"Dev",
	"Joe",
	"Will",
	"Peeter",
	"Annie",
	"Margret",
	"Marshal",
	"Mike",
	"Shaun",
	"James",
	"Robert",
	"Michael",
	"William",
	"David",
	"Richard",
	"Joseph",
	"Thomas",
	"Charles",
	"Daniel",
	"Matthew",
	"Anthony",
	"Mark",
	"Donald",
	"Steven",
	"Paul",
	"Andrew",
	"Joshua",
	"Kenneth",
	"Kevin",
	"Brian",
	"George",
	"Edward",
	"Ronald",
	"Timothy",
	"Jason",
	"Jeffrey",
	"Ryan",
	"Jacob",
	"Nicholas",
	"Benjamin",
	"Samuel",
	"Nathan",
	"Zachary",
	"Caleb",
	"Patrick",
	"Ethan",
}

var LastName = []string{
	"Smith",
	"Johnson",
	"Williams",
	"Brown",
	"Jones",
	"Garcia",
	"Miller",
	"Davis",
	"Rodriguez",
	"Martinez",
	"Hernandez",
	"Lopez",
	"Gonzalez",
	"Wilson",
	"Anderson",
	"Thomas",
	"Taylor",
	"Moore",
	"Jackson",
	"Martin",
	"Lee",
	"Perez",
	"Thompson",
	"White",
	"Harris",
	"Sanchez",
	"Clark",
	"Lewis",
	"Robinson",
	"Walker",
	"Young",
	"Allen",
	"King",
	"Wright",
	"Scott",
	"Torres",
	"Nguyen",
	"Hill",
	"Flores",
	"Green",
	"Adams",
	"Nelson",
	"Baker",
	"Hall",
	"Rivera",
	"Campbell",
	"Mitchell",
	"Carter",
	"Bhardwaj",
	"Sharma",
}

type address struct {
	City    string
	Country string
}

var Addresses = []address{
	{"New York", "USA"},
	{"Los Angeles", "USA"},
	{"Chicago", "USA"},
	{"Houston", "USA"},
	{"Phoenix", "USA"},
	{"London", "United Kingdom"},
	{"Manchester", "United Kingdom"},
	{"Birmingham", "United Kingdom"},
	{"Liverpool", "United Kingdom"},
	{"Edinburgh", "United Kingdom"},
	{"Toronto", "Canada"},
	{"Vancouver", "Canada"},
	{"Montreal", "Canada"},
	{"Calgary", "Canada"},
	{"Ottawa", "Canada"},
	{"Sydney", "Australia"},
	{"Melbourne", "Australia"},
	{"Brisbane", "Australia"},
	{"Perth", "Australia"},
	{"Adelaide", "Australia"},
	{"Berlin", "Germany"},
	{"Munich", "Germany"},
	{"Hamburg", "Germany"},
	{"Frankfurt", "Germany"},
	{"Cologne", "Germany"},
	{"Paris", "France"},
	{"Lyon", "France"},
	{"Marseille", "France"},
	{"Toulouse", "France"},
	{"Nice", "France"},
	{"Tokyo", "Japan"},
	{"Osaka", "Japan"},
	{"Kyoto", "Japan"},
	{"Nagoya", "Japan"},
	{"Sapporo", "Japan"},
	{"Mumbai", "India"},
	{"Delhi", "India"},
	{"Bengaluru", "India"},
	{"Hyderabad", "India"},
	{"Chennai", "India"},
	{"Dubai", "UAE"},
	{"Abu Dhabi", "UAE"},
	{"Sharjah", "UAE"},
	{"Singapore", "Singapore"},
	{"Seoul", "South Korea"},
	{"Beijing", "China"},
	{"Shanghai", "China"},
	{"Cape Town", "South Africa"},
	{"São Paulo", "Brazil"},
	{"Mexico City", "Mexico"},
}
